AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  An example RESTful service
Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: announcement-app-api-${StageName}
      StageName:
        Ref: StageName
      DefinitionBody:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: api/swagger.yaml
  CreateAnnouncementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: announcement-app-${StageName}-create-announcement
      CodeUri: api/
      Handler: handler.create_announcement
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: AnnouncementsTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: AnnouncementsTable
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /
            Method: POST

  ListAnnouncementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: announcement-app-${StageName}-list-announcements
      CodeUri: api/
      Handler: handler.list_announcements
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /
            Method: GET

  AnnouncementsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: announcement-app-${StageName}-announcements
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        stage:
          Ref: StageName